package org.brownmun.web.resources;

import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.type.TypeFactory;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Setter;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * Chunk entry generated by Lycaon AssetManifestPlugin
 */
@Data
public class Chunk
{
	public static final TypeReference<Map<String, Chunk>> CHUNK_MAP = new TypeReference<Map<String, Chunk>>() { };

	@JsonProperty
	private List<String> js = Lists.newArrayList();

	@JsonProperty
	private List<String> css = Lists.newArrayList();

	@Setter(AccessLevel.NONE)
	private Map<String, List<String>> other = Maps.newHashMap();

	@JsonAnySetter
	public void addFileType(String name, List<String> assets)
	{
		other.put(name, assets);
	}
}
