package org.brownmun.web.resources;

import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;

import java.util.List;
import java.util.Map;

/**
 * Chunk entry generated by Lycaon AssetManifestPlugin
 */
public class Chunk
{
	static final TypeReference<Map<String, Chunk>> CHUNK_MAP = new TypeReference<Map<String, Chunk>>() { };

	@JsonProperty
	private List<String> js = Lists.newArrayList();

	@JsonProperty
	private List<String> css = Lists.newArrayList();

	private Map<String, List<String>> other = Maps.newHashMap();

	@JsonAnySetter
	public void addFileType(String name, List<String> assets)
	{
		other.put(name, assets);
	}

	public static TypeReference<Map<String, Chunk>> getChunkMap()
	{
		return CHUNK_MAP;
	}

	public List<String> getJs()
	{
		return js;
	}

	public void setJs(List<String> js)
	{
		this.js = js;
	}

	public List<String> getCss()
	{
		return css;
	}

	public void setCss(List<String> css)
	{
		this.css = css;
	}

	public Map<String, List<String>> getOther()
	{
		return other;
	}
}
