version: '3.1'

services:
  database:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - 'dbvolume:/var/lib/postgresql/data'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

volumes:
  dbvolume: {}