version: '2'
services:
    postgres:
        image: postgres
        ports:
        - "5432:5432"
        volumes:
        - dbvolume:/var/lib/postgresql/data
        environment:
        - POSTGRES_PASSWORD=$DB_PASSWORD
        - POSTGRES_USER=$DB_USER
        - POSTGRES_DB=$DB_NAME
volumes:
    dbvolume: {}
