---

- name: Ensure the Docker DNF repository is configured
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Ensure Docker is installed
  dnf: name=docker-ce state=latest
  notify:
  - Restart Docker

- name: Ensure Docker configuration directory exists
  file: path=/etc/docker state=directory owner=root group=root mode=0644

- name: Configure Docker
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
  - Restart Docker

- name: Ensure Docker is running
  service: name=docker state=started enabled=yes
