---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: technology@busun.org
    privateKeySecretRef:
      name: letsencrypt-prod-key
    http01: {}