---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app: brownmun-test
  replicas: 2
  template:
    metadata:
      labels:
        app: brownmun-test
    spec:
      containers:
        - name: test-container
          image: brownmun-test:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: brownmun-test
  name: brownmun-test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: brownmun-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: brownmun-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - test.busun.org
      secretName: brownmun-test-tls
  rules:
    - host: test.busun.org
      http:
        paths:
          - path: /
            backend:
              serviceName: brownmun-test
              servicePort: 80