# Local / dev settings
spring:
  datasource:
    url: "${DB_JDBC_URL}"
    #url: 'jdbc:postgresql://foo/bar'
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"

logging:
  level:
    org.springframework.security: DEBUG
    org.brownmun: DEBUG

management:
  endpoints:
    web:
      expose: '*'

webpack:
  asset-base: http://localhost:9090/assets/
  reload: true

mail:
  from-address: no-reply@busun.org
  reply-to-address: technology@busun.org

mailgun:
  base-uri: https://api.mailgun.net/v3/mg.busun.org
  api-key: "${MAILGUN_API_KEY}"
