---

# This role only sets up the infrequently-changing parts of the conference, not things that change on
# every deploy

- name: Ensure {{ conference.name }} user exists
  user:
    name: "{{ conference.name }}"
    uid: "{{ conference.user_id }}"
    groups: docker
    create_home: no
    state: present
  

- name: Configure the systemd service for {{ conference.name }}
  template:
    src: conference.service.j2
    dest: /etc/systemd/system/{{ conference.name }}.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart backend

# Don't actually copy over any configuration, since
# that's done by the deploy play
- name: Ensure {{ conference.name }} configuration directory exists
  file:
    path: /etc/{{ conference.name }}
    state: directory
    owner: "{{ conference.name }}"
    mode: 0755

- name: Ensure {{ conference.name }} backend is running
  service: name={{ conference.name }} state=started enabled=yes
  