secretariat:
  members: []

mail:
  link-base: https://browncrisis.org
  from-address: admin@browncrisis.org
  reply-address: technology@busun.org

conference:
  decisions-public: false
  info-email: info@browncrisis.org
  name: BUCS
  logo-url: https://storage.googleapis.com/bucs_assets/bucs-logo.png
  facebook-url: https://facebook.com/browncrisis
  twitter-url: https://twitter.com/browncrisis
  events:
  - date: December 1, 2018
    description: Regular Registration Deadline
  - date: January 31, 2019
    description: Late Registration Deadline
  - date: March 1-3, 2019
    description: BUCS 2019

server:
  tomcat:
    accesslog:
      directory: /var/log/bucs
