secretariat:
  members:
  - title: Secretary-General
    name: Jordan Waller
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/jordan.jpg
    email: sg@busun.org
    bio: >
        Jordan Waller ('18) is the Co-Secretary General for BUSUN 2017. She is originally from Chicago, IL and
        is concentrating in Political Science and History. Outside of Brown Model United Nations, Jordan serves on
        the Interviews Board from the Brown Political Review and conducts research for a professor in the Political
        Science Department. This is Jordan's second year on the BUSUN Secretariat. As someone who has participated
        in Model United Nations since high school, she is excited to make sure BUSUN is an educational and enjoyable
        experience for all.

  - title: Secretary-General
    name: Cathy Bai
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/cathy.jpg
    email: sg@busun.org
    bio: >
        Cathy Bai (’19) is the Co-Secretary-General for BUSUN 2016. Cathy is a junior Computational Biology and
        Applied Mathematics-Economics (or maybe History) concentrator from China and Indonesia. When she’s not
        overcommitted to classes, she enjoys cooking, playing the classical guitar, and spending an absurd amount
        of time hunting for nice cafes in Providence. Cathy served as Director of General Committees for BUSUN 2016,
        and is looking forward to an even better conference this year.

  - title: Under-Secretary-General
    name: Beatriz Vianna
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/bia.jpg
    email: usg@busun.org
    bio: >
        Beatriz Vianna (’18) is excited to join the Secretariat as Under-Secretary-General for her fourth and
        final year of BUSUN. Bia is a senior Economics concentrator from Sao Paulo, Brazil, and has been doing
        Model UN since her sophomore year of high school. Outside of Model UN she is the co-President of
        Brownzilians, the Brazilian Students Association at Brown, is a Research Assistant for the
        Economics and Education Department, is a peer advisor for first-year students, and plays in the
        percussion group named Bloco da Brown. She is excited to come back for this year’s Secretariat, and is
        looking forward to an amazing BUSUN 2017!

  - title: Director General
    name: Colette Bare
    email: dg@busun.org
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/colette.jpg
    bio: >
        Colette Bare (’19) is the Director General for BUSUN 2017. Originally from Illinois, she is a
        junior studying electrical engineering with a focus on applications in health and human biology.
        Outside of her time competing with the Brown MUN travel team and organizing logistics for BUSUN XXI,
        you can find Colette working as a peer advisor, playing intramural soccer, running events with the
        Society of Women Engineers, or doing research in a neuro-engineering lab on campus. Colette has
        participated in Model UN since her freshman year of high school and is excited to make this BUSUN the
        best one yet!

  - title: Director of General Committees
    name: Zahra Asghar
    email: general@busun.org
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/zahra.jpg
    bio: >
        Zahra Asghar ('20) is the Director of General Committees for BUSUN 2017. She is a sophomore from Dubai,
        UAE concentrating in Cognitive Neuroscience and International Relations with a focus on the Middle East.
        She has participated in MUN since her freshman year at high school and has participated in all aspects of
        the Brown University Model United Nations program. When she's not doing MUN, she can be found working as
        a research assistant to find ways that neuroscience can be used to improve education and psychosocial
        support for refugees (or napping). She looks forward to a wonderful BUSUN XXI.

  - title: Director of Specialized and Historical Committees
    name: Margaret Follet
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/margaret.jpg
    email: spec@busun.org
    bio: >
        Margaret Follett (’19) is excited to serve as the Director of Specialized and Historical Committees
        for BUSUN XXI. Margaret is a junior concentrating in History and Computer Science. She hails from
        the tiny town of Boxborough, Massachusetts, for which she has a remarkable amount of town pride.
        Margaret served as the Director for the African Union at BUSUN XX, and is thrilled to return for
        another amazing conference. Outside of Model UN she volunteers for BruNotes, a musical outreach group
        to local public schools, and serves as an English tutor for Syrian refugees with the non-profit
        Paper Airplanes.

  - title: Director of Crisis Committees
    name: Adam DeHovitz
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/wind-turbine.jpg
    email: crisis@busun.org
    bio: >
        Adam DeHovitz ('19) is Director of Crisis Committees for this year's BUSUN. Adam is a New Yorker
        enjoying his time here at Brown, where he studies Computer Science. When he's not overworked he enjoys
        biking, reading about history, and being a teaching assistant in the CS department. Adam was Director of
        Technology as well as a Crisis Manager at last year's BUSUN, and has been involved in the conference since
        his sophomore year of high school when he first came as a delegate. He hopes that you'll enjoy the
        conference as much as he did.

  - title: Director of External Affairs
    name: Jourdan Smithwick
    email: info@busun.org
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/jourdan.jpg
    bio: >
        Jourdan Smithwick (’20) is proud to serve as the Director of External Affairs
        for BUSUN XXI. A sophomore from Long Island, New York hoping to
        concentrate independently, Jourdan has been involved with Model United
        Nations as a delegate since middle school. She now works to organize and staff
        conferences at Brown — having served as chair of Brazil in the six-committee
        joint crisis about global cybersecurity for BUSUN XX as well as chair of
        England 1066 for BUCS XI. Outside of all that she does for Brown Model
        United Nations, Jourdan volunteers as a tutor for incarcerated individuals with
        the Petey Greene program, advocates for gender equality, and makes playlists of
        which she is quite proud. She is looking forward to a successful conference and
        is available to address any questions or concerns at info@busun.org

  - title: Director of Outreach
    name: Anna Meyer
    email: outreach@busun.org
    image-address: https://placebear.com/200/200
    bio: >
        Anna Meyer ('18) is the Co-Director of Outreach for BUSUN 2017. Anna is a junior Education and American Studies
        concentrator from Massachusetts. She has been participating in MUN since high school and served as the
        Director of Outreach for BUSUN 2016. When she is not reading for class, Anna works as a research assistant
        in the Education department and volunteers in Providence Public Schools. She is so excited to welcome high
        schoolers to campus for some amazing debate!

  - title: Director of Outreach
    name: Elana Confino-Pinzon
    email: outreach@busun.org
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/elana.jpg
    bio: >
        Elana Confino-Pinzon (‘20) is delighted to join BUSUN 2017 as one of the Directors of Outreach.
        Elana is a sophomore from New York planning to concentrate in Political Science and Urban Studies.
        She has been involved with Model UN since her sophomore year of high school, and was a director for
        BUSUN last year.  Outside of Model UN, Elana is involved with the Brown Special Events Committee,
        and volunteers as a tutor at a local Providence elementary school.  On campus, she can be found
        working on art projects or listening to new musical soundtracks.

  - title: Director of Operations and Implementations
    name: Tess Rossi
    email: ops@busun.org
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/tess.jpg
    bio: >
        Tess Rossi ('20) is the Director of Operations for BUSUN 2017. Tess is a sophomore who
        has no idea what she wants to concentrate in, though she would bet $1 she will end up
        concentrating in Literary Arts. Tess is a native Rhode Islander and began participating in
        Model UN her junior year of high school. Outside of MUN, Tess is a part of Write It Brown, a novel
        writing club, and is employed by Brown's Alumni Relation Department, staffing events such as
        Alumni Fall Weekend and Reunion/Commencement Weekend. When she's not busy, Tess likes to explore
        photography, read sci-fi novels, and watch Netflix.

  - title: Director of Decorum
    name: Lily Zhao
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/lily.jpg
    email: decorum@busun.org
    bio: >
        Lily (Yiyu) Zhao (’18) is the Director of Decorum for BUSUN XXI. Lily comes from Beijing, China,
        but has also lived in various other cities including Shanghai, Guangzhou, and Vancouver. Lily is
        currently a senior concentrating in English Nonfiction Writing, Economics, and Visual Arts. Outside
        of Model UN, Lily enjoys writing, editing, and illustrating for the International Writers' Blog,
        being a part of the Chinese Students Association, and dancing with the Salsa Club. She also serves
        as a Meiklejohn Peer Advisor. Lily loves to read and to travel. She has previously served as the
        Director of Operations and Implementation, and as Co-Secretary-General on the BUSUN Secretariat
        and is looking forward to contributing to the conference in her capacity as Director of Decorum this year.

  - title: Director of Media
    name: Bethany Hung
    email: media@busun.org
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/bethany.jpg
    bio: >
        Bethany Hung (’19) is the Director of Media for BUSUN 2017. Although Bethany formally studies cognitive
        neuroscience here at Brown, she also gets very excited about organic chemistry and oceanography. When not
        doodling in Illustrator for BUSUN, she can be found doodling on her nails or on a whiteboard in the Sciences
        Library. Beyond BUSUN, she serves as media lead for Hack@Brown, Brown’s annual hackathon, creative director
        for B-SIDE Magazine, and communications director for Brown NARAL. Bethany also spends an inordinate amount
        of time in a basement researching visual cognition and staring into the darkness.

  - title: Director of Technology
    name: Ben Navetta
    email: technology@busun.org
    image-address: https://storage.googleapis.com/busun_assets/sec-photos/ben.jpg
    bio: >
        Ben Navetta ('19) is Director of Technology for BUSUN XXI. A lifelong New Englander, Ben comes from
        a small town in Massachusetts. As a junior at Brown, he loves studying computer science. Outside of BUSUN,
        he's one of the workshops leads for Hack@Brown, a teaching assistant in the computer science department, and
        the systems administrator for a computer vision research lab. When he has the time, Ben is passionate
        about coffee, baking, and classics. He got his first Model UN experience when a friend pulled him into
        staffing BUCS his freshman year.
