secretariat:
  members:
    - title: Secretary-General
      name: Zahra Asghar
      image-address: https://storage.googleapis.com/bucs_assets/sec-photos/zahra.jpg
      email: sg.2@browncrisis.org
      bio: >
        Zahra Asghar ('20) is the Co-Secretary General for BUCS VII. She is a sophomore from Dubai, UAE concentrating in
        Cognitive Neuroscience and International Relations with a focus on the Middle East. She has participated in MUN
        since her freshman year at high school and has participated in all aspects of the Brown University Model United
        Nations program. When she's not doing MUN, she can be found working as a research assistant to find ways that
        neuroscience can be used to improve education and psychosocial support for refugees (or napping). She looks
        forward to a wonderful BUCS VII.
    - title: Secretary-General
      name: Colette Bare
      image-address: https://storage.googleapis.com/bucs_assets/sec-photos/colette.jpg
      email: sg.1@browncrisis.org
      bio: >
        Colette Bare (‘19) is the Co-Secretary General for BUCS VII. A junior from Ann Arbor, Michigan, Colette studies
        biomedical engineering. Colette has been competing in Model UN since her freshman year of high school and loves
        Brown MUN - spending time as a delegate, Director General for BUSUN XXI, and working to make this BUCS the best
        yet. Outside of MUN, you can find Colette playing soccer with her intramural team, volunteering with the Society
        of Women Engineers, and doing research in a neuroengineering lab on campus. Colette enjoys spending her few
        spare moments running the hills of Providence and working on the New York Times Crossword puzzle. She can’t wait
        for BUCS 2018!
    - title: Under-Secretary-General
      name: Jason Claman
      image-address: https://storage.googleapis.com/bucs_assets/sec-photos/jason.jpg
      email: usg@browncrisis.org
      bio: >
        Jason Claman ('18) is the Under-Secretary-General for BUCS 2018. He studies Economics and Public Policy and is a
        proud New Jerseyan. When he is not busy with Model UN, Jason enjoys trying and photographing interesting foods,
        traveling the world, and being a coffee snob. He is also involved in the Alexander Hamilton Society and No
        Labels at Brown. In prior years, Jason has been a Chair at BUCS and a Crisis Manager at BUSUN, and has also
        competed on the Model UN circuit. Jason is sure that this will be the best BUCS yet, and looks forward to
        meeting everyone in March.
    - title: Director General
      name: Nate Kublin
      image-address: https://storage.googleapis.com/bucs_assets/sec-photos/nate.jpg
      email:
      bio: >
        Nathaniel Kublin (‘20) is the Director General for BUCS 2018. He is a chemistry concentrator from Tucson,
        Arizona, where he began his MUN career as a junior in high school. Since coming to Brown, he has traveled to
        multiple conferences, in addition to serving as a director for BUCS 2017. When he is not studying orgo or doing
        MUN, as rare as it is, he enjoys writing comedy and watching Jeopardy.
    - title: Director of Outreach
      name: Julia Bennani-Smires
      image-address: https://storage.googleapis.com/bucs_assets/sec-photos/julia.jpg
      email: outreach@browncrisis.org
      bio: >
        Julia Bennani-Smires (’20) is the Director of Outreach for BUCS 2018. She is a sophomore from Casablanca,
        Morocco, hoping to double concentrate in History and Comparative Literature in French and Spanish. Julia has
        been involved with Model United Nations for six years, and served as Director at BUSUN 2016 and Crisis Staffer
        at BUCS 2017. In between travels to conferences with the Brown MUN team, Julia loves to discover new cultures,
        from her course on law in Ancient Greece to her love of reggaetón music. She is excited to welcome delegates to
        Brown for another brilliant session of BUCS.
    - title: Director of Decorum
      name: Margaret Follett
      image-address: https://storage.googleapis.com/bucs_assets/sec-photos/margaret.jpg
      email:
      bio: >
        Margaret Follett (’19) is excited to serve as the Director of Decorum for BUCS. Margaret is a junior
        concentrating in History and Computer Science. She hails from the tiny town of Boxborough, Massachusetts, for
        which she has a remarkable amount of town pride. Margaret served as the co-chair of the Generalitat of
        Catalonia in 2017, and is thrilled to return for another amazing conference. Outside of Model UN she volunteers
        for BruNotes, a musical outreach group to local public schools, and serves as an English tutor for Syrian
        refugees with the non-profit Paper Airplanes.
    - title: Director of Media
      name: Alex Mukai
      image-address: https://storage.googleapis.com/bucs_assets/sec-photos/alex.jpg
      email:
      bio: >
        Alex Mukai (’20) is the Director of Media for BUCS 2017. Alex is a sophomore from Cape Elizabeth, Maine
        interested in concentrating in international relations. He has been an avid participant in MUN since his
        freshman year of high school, and has thoroughly enjoyed continuing his MUN experience while at Brown — chairing
        the Syrian National Council committee for last year’s BUSUN, staffing last year’s Korea committee at BUCS, and
        traveling to conferences with the Brown MUN team. Outside of MUN, Alex has written for the Brown Political
        Review, swims for the Brown club swim team, and actively participates in homeless outreach programs in the
        Providence area. He looks forward to interacting with the delegates and hopes to help make BUCS 2018 the most
        successful BUCS yet!

mail:
  link-base: https://browncrisis.org
  from-address: admin@browncrisis.org
  reply-address: technology@busun.org

conference:
  decisions-public: false
  info-email: info@browncrisis.org
  name: BUCS
  logo-url: https://storage.googleapis.com/bucs_assets/bucs-logo.png
  facebook-url: https://facebook.com/browncrisis
  twitter-url: https://twitter.com/browncrisis
  events:
  - date: December 1, 2018
    description: Regular Registration Deadline
  - date: January 31, 2019
    description: Late Registration Deadline
  - date: March 1-3, 2019
    description: BUCS 2019

server:
  tomcat:
    accesslog:
      directory: /var/log/bucs
