spring:
    thymeleaf:
        mode: "HTML"
    datasource:
      url: ${DB_JDBC_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    mvc:
      favicon:
        enabled: true


server:
    compression:
        enabled: true
        mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"

sso:
    allowedDomains:
        - busun.org
    allowedEmails: []
    grantedAuthorities:
        - ROLE_USER
        - ROLE_STAFF
        - ROLE_ACTUATOR


google:
    client:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        preferTokenInfo: true

mailgun:
  base-uri: https://api.mailgun.net/v3/mg.busun.org
  api-key: ${MAILGUN_API_KEY}

mail:
    templateLocation: "classpath:/emails/"

logging:
  level:
    org.brownmun: trace