security:
  require-ssl: true
  headers:
    content-security-policy: default-src 'self'; base-uri 'self'; script-src 'self' cdnjs.cloudflare.com use.typekit.net; connect-src 'self' performance.typekit.net; img-src 'self' storage.googleapis.com p.typekit.net placebear.com; style-src 'self' 'unsafe-inline' use.typekit.net; font-src 'self' use.typekit.net fonts.typekit.net; child-src 'self' mapsengine.google.com www.google.com

server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    accesslog:
      enabled: true
      request-attributes-enabled: true
logging:
  level:
    org.brownmun: debug
