spring:
    thymeleaf:
        mode: "HTML"

server:
    compression:
        enabled: true
        mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"

google:
    client:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        preferTokenInfo: true
