mail:
  link-base: https://browncrisis.org
  from-address: admin@browncrisis.org
  reply-address: technology@busun.org

conference:
  decisions-public: false
  name: BUCS

server:
  tomcat:
    accesslog:
      directory: /var/log/bucs
