---

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  jackson:
    mapper:
      default_view_inclusion: true