---
# This play deploys a new version of a conference backend.
#
# Usage:
#    ansible-playbook deploy-conference.yml -e "conference=busun tag=abcdefg"

- hosts: brownmun
  tasks:
  - name: Update configured version
    copy:
      dest: /etc/{{ conference | mandatory }}/version
      content: "VERSION={{ tag | quote }}"
      owner: "{{ conference }}"
    become: yes
    become_user: "{{ conference }}"
  - name: Update asset server version
    copy:
      dest: /etc/asset-server/version
      content: "VERSION={{ tag | quote }}"
    become: yes
  # - name: Pull Docker images
    # docker_image: name={{ item }}
    # with_items:
      # - gcr.io/busun-158105/{{ conference }}:{{ tag }}
      # - gcr.io/busun-158105/ui:{{ tag }}
    # become: no
  - name: Restart service
    service: name={{ conference }} state=restarted
    become: yes
